apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainframe-deployment
spec:
  replicas: 3  # Adjust based on your requirement
  selector:
    matchLabels:
      app: mainframe
  template:
    metadata:
      labels:
        app: mainframe
    spec:
      containers:
      - name: mainframe
        image: registry.digitalocean.com/farabix/mainframe:latest  # Replace with your Docker image

        ports:
        - containerPort: 8000  # FastAPI runs on port 8000
