version: '3.4'

services:
  mainframe:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5198:80"
    image: registry.digitalocean.com/farabix/mainframe:latest