"""updated media

Revision ID: 4568de512927
Revises: 763c09cbee93
Create Date: 2023-12-14 08:24:25.593455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4568de512927'
down_revision: Union[str, None] = '763c09cbee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('media', sa.Column('fileName', sa.String(length=100), nullable=False))
    op.add_column('media', sa.Column('fileExtension', sa.String(length=20), nullable=False))
    op.drop_column('media', 'mediaUrl')
    op.drop_column('media', 'isVideo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('isVideo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('mediaUrl', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('media', 'fileExtension')
    op.drop_column('media', 'fileName')
    op.drop_column('media', 'type')
    # ### end Alembic commands ###
