"""reshaped news corporations

Revision ID: 57bec40fbb42
Revises: 8baf3810bb88
Create Date: 2023-12-25 07:36:10.320781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57bec40fbb42'
down_revision: Union[str, None] = '8baf3810bb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('fullName', sa.String(length=100), nullable=True))
    op.add_column('newsCorporations', sa.Column('shortName', sa.String(length=100), nullable=True))
    op.add_column('newsCorporations', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('newsCorporations_ibfk_1', 'newsCorporations', type_='foreignkey')
    op.create_foreign_key(None, 'newsCorporations', 'countries', ['country_id'], ['id'])
    op.drop_column('newsCorporations', 'organizationName')
    op.drop_column('newsCorporations', 'language_id')
    op.drop_column('newsCorporations', 'parentOrganization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('parentOrganization', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('newsCorporations', sa.Column('language_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('newsCorporations', sa.Column('organizationName', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'newsCorporations', type_='foreignkey')
    op.create_foreign_key('newsCorporations_ibfk_1', 'newsCorporations', 'languages', ['language_id'], ['id'])
    op.drop_column('newsCorporations', 'country_id')
    op.drop_column('newsCorporations', 'shortName')
    op.drop_column('newsCorporations', 'fullName')
    # ### end Alembic commands ###
