"""adding createdAt and updatedAt to all models

Revision ID: 5980d4f371b3
Revises: a8e257e00a15
Create Date: 2023-12-03 09:34:57.310829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5980d4f371b3'
down_revision: Union[str, None] = 'a8e257e00a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cities', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('continents', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('continents', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('countries', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('countries', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('languages', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('languages', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provinces', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('provinces', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provinces', 'updatedAt')
    op.drop_column('provinces', 'createdAt')
    op.drop_column('languages', 'updatedAt')
    op.drop_column('languages', 'createdAt')
    op.drop_column('countries', 'updatedAt')
    op.drop_column('countries', 'createdAt')
    op.drop_column('continents', 'updatedAt')
    op.drop_column('continents', 'createdAt')
    op.drop_column('cities', 'updatedAt')
    op.drop_column('cities', 'createdAt')
    # ### end Alembic commands ###
