"""changed newscorporation

Revision ID: 5b7260083925
Revises: f82d7bbb5ebf
Create Date: 2023-12-27 08:26:37.362991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b7260083925'
down_revision: Union[str, None] = 'f82d7bbb5ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('logo', sa.String(length=300), nullable=True))
    op.drop_column('newsCorporations', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('icon', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('newsCorporations', 'logo')
    # ### end Alembic commands ###
