"""adding the default createdAt and updatedAt to news model

Revision ID: 91642eb4678d
Revises: 2d368e1d4809
Create Date: 2024-01-15 17:30:07.973729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91642eb4678d'
down_revision: Union[str, None] = '2d368e1d4809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('news', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'updatedAt')
    op.drop_column('news', 'createdAt')
    # ### end Alembic commands ###
