"""increasing the size of content of new

Revision ID: 934f6468852d
Revises: eafc108bd327
Create Date: 2023-12-30 07:48:27.517578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '934f6468852d'
down_revision: Union[str, None] = 'eafc108bd327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.String(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###
