"""change the content of the news to text from varchar

Revision ID: 9758f2451c56
Revises: 00b6691e88c6
Create Date: 2023-12-30 20:58:15.610785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9758f2451c56'
down_revision: Union[str, None] = '00b6691e88c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###
