"""reshaped news corporations

Revision ID: b897bfe0921e
Revises: 57bec40fbb42
Create Date: 2023-12-25 07:53:28.624888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b897bfe0921e'
down_revision: Union[str, None] = '57bec40fbb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_constraint('newsCorporations_ibfk_1', 'newsCorporations', type_='foreignkey')
    op.drop_column('newsCorporations', 'country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsCorporations', sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('newsCorporations_ibfk_1', 'newsCorporations', 'countries', ['country_id'], ['id'])
    op.drop_column('newsCorporations', 'country')
    # ### end Alembic commands ###
