"""commenting out some of the writers

Revision ID: d4fb0b14b9a2
Revises: 4568de512927
Create Date: 2023-12-16 17:03:03.425754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4fb0b14b9a2'
down_revision: Union[str, None] = '4568de512927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('review_media')
    op.drop_table('news_writer')
    op.drop_index('ix_reviews_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('email', table_name='writers')
    op.drop_index('username', table_name='writers')
    op.drop_constraint('writers_ibfk_2', 'writers', type_='foreignkey')
    op.drop_column('writers', 'resume_id')
    op.drop_column('writers', 'email')
    op.drop_column('writers', 'linkedin_profile')
    op.drop_column('writers', 'password')
    op.drop_column('writers', 'username')
    op.drop_column('writers', 'past_experience_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('past_experience_url', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('writers', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('writers', sa.Column('password', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('writers', sa.Column('linkedin_profile', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('writers', sa.Column('email', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('writers', sa.Column('resume_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('writers_ibfk_2', 'writers', 'media', ['resume_id'], ['id'])
    op.create_index('username', 'writers', ['username'], unique=False)
    op.create_index('email', 'writers', ['email'], unique=False)
    op.create_table('reviews',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('writer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=800), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='reviews_ibfk_1'),
    sa.ForeignKeyConstraint(['writer_id'], ['writers.id'], name='reviews_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_id', 'reviews', ['id'], unique=False)
    op.create_table('news_writer',
    sa.Column('writer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='news_writer_ibfk_1'),
    sa.ForeignKeyConstraint(['writer_id'], ['writers.id'], name='news_writer_ibfk_2'),
    sa.PrimaryKeyConstraint('writer_id', 'news_id')
    )
    op.create_table('review_media',
    sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='review_media_ibfk_1'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='review_media_ibfk_2'),
    sa.PrimaryKeyConstraint('review_id', 'media_id')
    )
    op.create_table('feedback',
    sa.Column('writer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='feedback_ibfk_1'),
    sa.ForeignKeyConstraint(['writer_id'], ['writers.id'], name='feedback_ibfk_2'),
    sa.PrimaryKeyConstraint('writer_id', 'news_id')
    )
    # ### end Alembic commands ###
