"""change the category

Revision ID: e07fd5869457
Revises: d4fb0b14b9a2
Create Date: 2023-12-18 09:33:20.076138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e07fd5869457'
down_revision: Union[str, None] = 'd4fb0b14b9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_ibfk_1', 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_ibfk_1', 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###
