name: deploy image

on:
  push:
    branches: [ "main" ]  # Trigger on push to main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install libmagic1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest

    # Docker build steps for custom and latest tag
    - name: Build Docker image
      run: |
        docker build -t registry.digitalocean.com/farabix/mainframe:latest -t registry.digitalocean.com/farabix/mainframe:$GITHUB_SHA .

    - name: Install doctl
      run: |
        wget https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz
        tar xf doctl-1.64.0-linux-amd64.tar.gz
        sudo mv doctl /usr/local/bin

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 600
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    # Push both tags to the registry
    - name: Push Docker image to registry
      run: |
        docker push registry.digitalocean.com/farabix/mainframe:latest
        docker push registry.digitalocean.com/farabix/mainframe:$GITHUB_SHA
