name: Deployment

on:
  push:
    branches:
      - main
      - stage

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Production
        run: echo "Deploying to production environment..."

      - name: Deploy to Stage
        run: echo "Deploying to stage environment..."

      - name: Install libmagic
        run: |
          sudo apt-get update
          sudo apt-get install libmagic1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with pytest
        run: |
          pytest

  deploy_to_stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    environment: stage
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Stage
        run: echo "Deploying to stage environment..."

      - name: Install libmagic
        run: |
          sudo apt-get update
          sudo apt-get install libmagic1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with pytest
        run: |
          pytest
