name: general tests

on:
  push:
    branches-ignore:
      - 'main'  # Exclude 'main' here because it's covered by pull_request
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install libmagic1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL='mysql+pymysql://doadmin:AVNS_5cCBDwuj8XRQkndnlJX@stage-do-user-14956565-0.c.db.ondigitalocean.com:25060/defaultdb'" >> $GITHUB_ENV
        echo "DATABASE_USERNAME='doadmin'" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD='AVNS_5cCBDwuj8XRQkndnlJX'" >> $GITHUB_ENV
        echo "DATABASE_HOST='stage-do-user-14956565-0.c.db.ondigitalocean.com'" >> $GITHUB_ENV
        echo "DATABASE_PORT=25060" >> $GITHUB_ENV
        echo "DATABASE_NAME='defaultdb'" >> $GITHUB_ENV
        echo "SECRET_KEY='e387952c4fa241f772a65daa93cd21217c3da6e2e1a4a8eb78832c464855e5ee'" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID='DO00ZZZ2G9DPWR8ZUA3J'" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY='FW4bSkjLHR/Ad633aFjpqC8YsCRxDjVddbZZNJEptw0'" >> $GITHUB_ENV
        echo "NEWS_DATA_TO_API_KEY='pub_335322fdff4a6749083e621c7fb413696b162'" >> $GITHUB_ENV
        echo "OPENAI_API_KEY='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'" >> $GITHUB_ENV

    - name: Test with pytest
      run: |
        pytest
