name: general tests

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install libmagic1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Determine Environment
      id: set-env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "::set-output name=env::production"
        elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "::set-output name=env::stage"
        else
          echo "::set-output name=env::unknown"
        fi

    - name: Echo Environment
      run: echo "Running in the ${{ steps.set-env.outputs.env }} environment"

    - name: Test with pytest
      run: |
        pytest
