name: general tests

on:
  push:
    branches-ignore:
      - 'main'  # Exclude 'main' here because it's covered by pull_request
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set environment variables  
      run: |
        echo "${{ secrets.DATABASE_URL }} - ${{ DATABASE_URL }}"
        export DATABASE_URL="${{ DATABASE_URL }}"
        export DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}"
        export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
        export DATABASE_HOST="${{ secrets.DATABASE_HOST }}"
        export DATABASE_PORT="${{ secrets.DATABASE_PORT }}"
        export DATABASE_NAME="${{ secrets.DATABASE_NAME }}"
        export SECRET_KEY="${{ secrets.SECRET_KEY }}"
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export NEWS_DATA_TO_API_KEY="${{ secrets.NEWS_DATA_TO_API_KEY }}"
        export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"

    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install libmagic1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest